{
    'name': 'Enterprise Backend Theme',
    'version': '17.0.1.2.0',
    'category': 'Themes/Backend',
    'summary': 'Enterprise-style Backend Theme for Odoo Community - White Navbar, App Icons, Login Page, Tiles, and Header Search',
    'author': 'Smart System for Information Technology',
    'maintainer': 'Smart System for Information Technology',
    'support': 'info@smartsystem.sa',
    'website': 'https://smartsystem.sa',
    'license': 'LGPL-3',
    'depends': ['base', 'web'],
    'data': [
        'views/res_config_settings.xml',
        'views/templates.xml',
    ],
    'post_init_hook': None,
    'assets': {
        'web.assets_backend': [
            'ss_enterprise_theme/static/src/js/home_menu.js',
            'ss_enterprise_theme/static/src/js/home_menu_root.js',
            'ss_enterprise_theme/static/src/js/app_grid.js',
            'ss_enterprise_theme/static/src/js/app_tile.js',
            'ss_enterprise_theme/static/src/js/search_bar.js',
            'ss_enterprise_theme/static/src/js/theme_manager.js',
            'ss_enterprise_theme/static/src/webclient/webclient.js',
            'ss_enterprise_theme/static/src/webclient/menus/app_menu_service.js',
            'ss_enterprise_theme/static/src/webclient/appsbar/appsbar.js',
            'ss_enterprise_theme/static/src/webclient/appsmenu/appsmenu.scss',
            'ss_enterprise_theme/static/src/webclient/appsbar/appsbar.scss',
            'ss_enterprise_theme/static/src/css/backend_theme.css',
            'ss_enterprise_theme/static/src/scss/grid.scss',
            'ss_enterprise_theme/static/src/scss/themes.scss',
            'ss_enterprise_theme/static/src/scss/responsive.scss',
        ],
        'web.assets_frontend': [
            'ss_enterprise_theme/static/src/css/login_theme.css',
        ],
    },
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
}
